version: '3'

services:
  shared_rabbitmq:
    container_name: codely-php_ddd_skeleton-rabbitmq
    image: 'rabbitmq:3.10.5-management'
    restart: unless-stopped
    ports:
      - "5630:5672"
      - "8090:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=codely
      - RABBITMQ_DEFAULT_PASS=c0d3ly

  mooc_mysql:
    container_name: codely-php_ddd_skeleton-mooc-mysql
    image: mariadb:10.7.4
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]

  mooc_backend_php:
    container_name: codely-php_ddd_skeleton-mooc_backend-php
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8030:8030"
      - "9030:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
      - mooc_mysql
    command: symfony serve --dir=apps/mooc/backend/public --port=8030
